name: Generate Keystore (run once)

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Generate and print keystore as base64
        run: |
          keytool -genkeypair \
            -alias tempkey \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -keystore binaryeye-odk.keystore \
            -storepass password \
            -keypass password \
            -dname "CN=BinaryEye-ODK"
          base64 -w 0 binaryeye-odk.keystore
